version: "3.7"

services:
  db:
    image: mysql:${DB_TAG}
    container_name: "${PROJECT_NAME}-db"
    #volumes:
      #- ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
     - "3306:3306"
  app:
    #build: .
    image: sxe79/docebo:latest
    container_name: "${PROJECT_NAME}-app"
    depends_on:
      - db
    ports:
     - "80:80"
    volumes:
     - ./Back:/var/www/html